title: YouYou's Home
description: Homepage of YouYou


location: >
  Nanjing, China.

# Pages shown in navbar
nav_pages:
  - name: album
  - name: travel

collections:
  album:
    output: true
  travel:
    output: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
usemathjax: true

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
  syntax_highlighter: rouge
